export const usersList = [
    {
        id: '544143241',
        name: 'Bartosz',
        surname: 'Kowalski',
        email: 'test',
        password: 'test',
        role: 'admin',
    },
    {
        id: '123456789',
        name: 'John',
        surname: 'Doe',
        email: 'john.doe@example.com',
        password: 'password123',
        role: 'admin',
    },
    {
        id: '987654321',
        name: 'Emily',
        surname: 'Smith',
        email: 'emily.smith@example.com',
        password: 'securepass',
        role: 'admin',
    },
    {
        id: '246813579',
        name: 'Sarah',
        surname: 'Johnson',
        email: 'sarah.johnson@example.com',
        password: 'abc123',
        role: 'admin',
    },
    {
        id: '789456123',
        name: 'Michael',
        surname: 'Brown',
        email: 'michael.brown@example.com',
        password: 'p@ssw0rd',
        role: 'admin',
    },
    {
        id: '987654321',
        name: 'Emma',
        surname: 'Davis',
        email: 'emma.davis@example.com',
        password: 'qwerty123',
        role: 'admin',
    },
    {
        id: '456123789',
        name: 'Daniel',
        surname: 'Wilson',
        email: 'daniel.wilson@example.com',
        password: 'letmein',
        role: 'admin',
    },
    {
        id: '789123456',
        name: 'Sophia',
        surname: 'Taylor',
        email: 'sophia.taylor@example.com',
        password: 'pass1234',
        role: 'admin',
    },
    {
        id: '852369741',
        name: 'Oliver',
        surname: 'Anderson',
        email: 'oliver.anderson@example.com',
        password: 'test456',
        role: 'admin',
    },
    {
        id: '963852741',
        name: 'Ava',
        surname: 'Thomas',
        email: 'ava.thomas@example.com',
        password: 'mysecret',
        role: 'admin',
    }
];
