
import { Providers } from "@/redux/provider";
import { GlobalStyles } from "@/styles/Global";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GlobalStyles />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
